version: '3.4'
services:
  morocco_jobs:
    image: 127.0.0.1:5000/morocco_jobs:latest
    expose:
      - 80
    environment:
      - DB=mongodb://root:phd_2020@127.0.0.1:29098/morocco_jobs?authMechanism=DEFAULT&authSource=admin
    ports:
      - 8901:80
    deploy:
      # placement:
      #   constraints:  [node.hostname != v1-mtm-manager-1]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"  
        - "traefik.http.routers.morocco_jobs.tls.certresolver=let"
        - "traefik.http.routers.morocco_jobs.entrypoints=websecure"
        - "traefik.http.services.morocco_jobs.loadbalancer.server.port=8901"
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 1s
    networks:
      - public
networks:
    public:
       external: true


